### ISSUE TITLE
browserList Configuration doesn't work

### ISSUE THREAD

**Issue by etrinh** [BenAAndrew/browser-compatibility-checker#4]
Hi,
Thanks for this great extension,
I just noticed that the configuration option `browserList` doesn't seem to work, I am wondering if there isn't a mismatch with 
`browsersToCheck` which is used in the code?

Thanks!

**Comment by BenAAndrew** [comment]
Hi,
Good find, the issue should now be fixed in version 1.1.2.

Thanks for your feedback!
